### PR TITLE
fix: fix padding direction bug in BasicBlockNode

### LINKED ISSUE #2295: Incorrect decorator index mapping due to NOOPs
I believe the core issue from #2181 hasn't been fully resolved with #2195. Consider the following program:

```
begin
    push.4
    push.8
    drop
    drop

    repeat.12
        push.42
    end

    debug.stack.15  # <=== incorrect
    dropw dropw dropw dropw
end
```

We would expect the `debug.stack` decorator to print out the first *12* elements to be `42`, but it only prints 11:

```
Stack state in interval [0, 14] before step 21:
├──  0: 42
├──  1: 42
├──  2: 42
├──  3: 42
├──  4: 42
├──  5: 42
├──  6: 42
├──  7: 42
├──  8: 42
├──  9: 42
├── 10: 42
├── 11: 0
├── 12: 0
├── 13: 0
├── 14: 0
└── (12 more items)
```

I'm not sure if this is completely minimal, or what exactly is the edge case that makes the current implementation fail. I double-checked that this was also failing after [bd9564c](https://github.com/0xMiden/miden-vm/commit/bd9564c03a9841e66abb314d6f210831dcdd253f).

### PR DESCRIPTION
**Pull request by huitseeker**
The issue was that `DecoratorPaddingOffsets` was being used in "reverse" for both raw -> padded and padded -> raw conversions, causing sign/direction confusion. The padding and un-padding operations were tested to be inverses of each other, but both code paths were using offsets in the wrong direction, which did not allow that round-trip to catch the bug.

Fixes #2295 

## Solution 

Implemented two explicit, unambiguous prefix arrays:

### RawToPaddedPrefix
- Domain: raw operation indices
- Meaning: count of padding ops strictly before raw index r
- Usage:  (addition)

### PaddedToRawPrefix
- Domain: padded operation indices (equivalent to old DecoratorPaddingOffsets)
- Meaning: count of padding ops strictly before padded index p
- Usage:  (subtraction)

## Tests

- tested in variants using proptests for each direction.
- maintained the round-trips so that un-padding is the inverse of padding.
- specific test reproducing issue 2295.

### CODE REVIEW

File: core/src/mast/node/basic_block_node/mod.rs [hunk 1]
```diff
@@ -759,62 +747,142 @@ pub(crate) fn validate_decorators(operations_len: usize, decorators: &DecoratorL
...
 }
 
-#[doc(hidden)]
-impl Index<usize> for DecoratorPaddingOffsets {
+/// Get the number of padding operations before raw index r.
+impl core::ops::Index<usize> for RawToPaddedPrefix {
     type Output = usize;
+    #[inline]
+    fn index(&self, idx: usize) -> &Self::Output {
+        &self.0[idx]
```
Comment (adr1anh) [inline core/src/mast/node/basic_block_node/mod.rs:811]: Should we panic if accessing the sentinel?

Comment (huitseeker) [reply core/src/mast/node/basic_block_node/mod.rs:811]: We do in fact voluntarily access it, something we document a few lines above when populating a value for it. I should perhaps move that comment ...

Comment (plafer) [reply core/src/mast/node/basic_block_node/mod.rs:811]: Do we want to move the comment? Otherwise this is good to merge
