### PR TITLE
fix(assembly): validate procedure roots during library deserialization

### LINKED ISSUE #2831: Library deserialization accepts uncallable procedure exports
When deserializing a `Library`, the loader accepts procedure exports that are not procedure roots. These exports cannot be invoked via `call` or `exec` because the VM only permits entry at procedure roots.

This is tracked in related issues:
- #2726 — feat: MAST forest deserialization
- #2292 — Refactor MastForest deserialization to TypeState pattern

The deserializer should validate that each exported `MastNodeId` is a procedure root (has no parent in the forest). Non-root nodes should be rejected at load time rather than failing silently at invocation.

Fix: during library deserialization, check that exported procedure node IDs are roots in their respective `MastForest`.

### PR DESCRIPTION
**Pull request by giwaov**
## Description

This PR fixes an issue where \Library::read_from\ accepts procedure exports whose \MastNodeId\ is not a procedure root in the underlying MAST forest. This allows crafting a library with uncallable procedure exports, violating the invariant enforced by \Library::new()\.

This was identified as finding 19 in the audit report.

### Fix
- Added a validation loop to the \Deserializable\ implementation for \Library\ (in \crates/assembly-syntax/src/library/mod.rs\) that checks each procedure export references a valid procedure root in the \MastForest\, matching the existing check in \Library::new()\.

### Test
- Added \library_deserialization_rejects_non_root_export\ test that constructs a tampered serialized library with an export pointing to a non-root node and verifies deserialization rejects it with an appropriate error message.

## Testing

- \cargo test -p miden-assembly library_deserialization_rejects_non_root_export\ passes
- \cargo test -p miden-assembly library_serialization\ still passes (no regression)
- Both \miden-assembly\ and \miden-assembly-syntax\ crates compile cleanly

Closes #2831

### CODE REVIEW

**Comment by amathxbt** [comment]
## Review: PR #2933 — Validate procedure roots during library deserialization

**Overall: 🟡 Correct logic, two CI blockers need fixing.**

Fixes issue #2831.

---

### Core Logic — ✅ Correct

The validation loop added in `crates/assembly-syntax/src/library/mod.rs`:

```rust
for export in exports.values() {
    if let LibraryExport::Procedure(ProcedureExport { node, path, .. }) = export
        && !mast_forest.is_procedure_root(*node)
    {
        return Err(DeserializationError::InvalidValue(format!(
            "invalid export: no procedure root for {path} procedure"
        )));
    }
}
```

**Placement is correct** — happens after all exports are read, before `compute_nodes_commitment`, so a malformed input is rejected before the digest is computed. The use of `if let ... && ...` (let-chains) is fine since the project targets edition 2024 / Rust ≥ 1.90 where let-chains are stable.

---

### CI Failures — 🔴 Must Fix Before Merge

**1. Missing CHANGELOG entry** (job: `changelog`)

The diff contains no `CHANGELOG.md` modification. The CI changelog check fails because there is no entry for this fix. Add an entry under **Bug Fixes** in the current release section, e.g.:

```markdown
- Library deserialization now rejects exports whose `MastNodeId` is not a procedure root, closing a silent-failure path ([#2933](https://github.com/0xMiden/miden-vm/pull/2933)).
```

**2. Nightly rustfmt failures** (job: `rustfmt check nightly on ubuntu-latest`)

Two issues in `crates/assembly/src/tests.rs`:

**(a) Split `use` statements need merging** (reported at line ~412).

Current:
```rust
use miden_core::mast::{BasicBlockNodeBuilder, MastForestContributor};
use miden_core::serde::ByteWriter;
```

nightly rustfmt expects:
```rust
use miden_core::{
    mast::{BasicBlockNodeBuilder, MastForestContributor},
    serde::ByteWriter,
};
```

**(b) `assert!` macro needs reformatting** (reported at line ~455).

Current:
```rust
assert!(result.is_err(), "deserialization should reject exports referencing non-root nodes");
```

nightly rustfmt breaks this onto multiple lines:
```rust
assert!(
    result.is_err(),
    "deserialization should reject exports referencing non-root nodes"
);
```

---

### Test Quality — ✅ Good

The test `library_deserialization_rejects_non_root_export` takes the right approach: it builds a valid library, manually serializes tampered bytes (a forest with a non-root node referenced as an export), and asserts both that deserialization fails **and** that the error message contains `"no procedure root"`. Both assertions are necessary and meaningful.

---

### Informational Note (pre-existing, out of scope)

`Library::read_from` uses the **trusted** `MastForest::read_from` deserializer rather than `UntrustedMastForest` (which recomputes digests). This is a pre-existing concern tracked in #2726 / #2292 and is out of scope here, but worth noting for future hardening.

---

**Summary: fix the CHANGELOG entry and run `cargo +nightly fmt` on the test file, then this is ready.**

**Comment by huitseeker** [comment]
@amathxbt Please cease spam comments.

**Review by huitseeker — APPROVED** [review]
🙏

**Review by bitwalker — APPROVED** [review]

**Comment by bitwalker** [comment]
@giwaov Can you rebase this and resolve the CHANGELOG conflict? I think we can get this merged once that is done

**Comment by giwaov** [comment]
﻿Rebased onto the latest `next` and force-pushed the branch.

I also reran the regression test locally:
- `cargo test -p miden-assembly library_deserialization_rejects_non_root_export`

That passes now, so this should be ready for another look.

File: crates/assembly-syntax/src/library/mod.rs [hunk 1]
```diff
@@ -648,6 +648,16 @@ impl Deserializable for Library {
             exports.insert(path, export);
         }
 
+        for export in exports.values() {
```
Comment (huitseeker) [inline crates/assembly-syntax/src/library/mod.rs]: I wonder if this should call `Library::new(mast_forest, exports)` instead of re-checking roots here. The last bug came from deserialization drifting away from the constructor path, and keeping the invariant and digest logic in one place would make the next validation change harder to miss.

Comment (giwaov) [reply crates/assembly-syntax/src/library/mod.rs]: Updated on the branch now. Library::read_from delegates to Self::new(mast_forest, exports) so the procedure-root invariant and digest computation stay on the constructor path instead of drifting here again.

I also re-ran cargo test -p miden-assembly library_deserialization_rejects_non_root_export locally.

Comment (huitseeker) [reply crates/assembly-syntax/src/library/mod.rs]: Lol. Good bot

Comment (giwaov) [reply crates/assembly-syntax/src/library/mod.rs]: Haha, fair enough 😄 Thanks again for the review and for merging this one.

That makes 10 merged PRs on my side now, which I’m really happy about and would love to do more, I also wanted to ask: when Miden eventually goes mainnet, is there likely to be any kind of recognition or reward for contributors, or is it still too early to say? Thank you sir.
