### PR TITLE
fix(assembly): correct cycle detection in toposort_caller

### LINKED ISSUE #2827: toposort_caller cycle check is incorrect
In `crates/assembly-syntax/src/sema/passes/toposort.rs:73`, the cycle detection logic for `toposort_caller` checks:

```rust
if visited.contains(&target) {
    return Err(SemanticAnalysisError::CycleInCallGraph { span: node_span });
}
```

This does not distinguish between nodes on the current DFS path (actual cycles) and nodes visited in earlier branches (DAG edges). The check should use a "currently visiting" set that tracks nodes on the recursion stack, not all visited nodes.

As a result, valid call graphs with shared callees may incorrectly report a cycle. The current code works in practice because the visitor is invoked per-procedure, so cross-branch revisits are rare, but the logic is fragile.

Fix: introduce a `visiting: HashSet<NodeId>` that is populated before recursing and cleared after, and check `visiting.contains(&target)` instead of `visited`.

### PR DESCRIPTION
**Pull request by crazywriter1**
## Summary
- Fix cycle detection in `CallGraph::toposort_caller` by using Kahn's algorithm invariant (`output.len() != graph.nodes.len()`) instead of checking edges only for nodes already in the output list. This avoids false positives when edges remain on nodes that were never popped into `output`.

Fixes #2827

## Notes (file location)
The issue description references `crates/assembly-syntax/src/sema/passes/toposort.rs`, but in the current `next` branch the relevant implementation lives in:
- `crates/assembly/src/linker/callgraph.rs`

I found it by searching the repository for `toposort_caller`.

## Test plan
- cargo test -p miden-assembly
- cargo clippy -p miden-assembly --all-targets --all-features -- -D warnings

### CODE REVIEW

**Comment by crazywriter1** [comment]
CI workflows require approval to run (fork PR). Can a maintainer approve the workflows?

File: crates/assembly/src/linker/callgraph.rs [hunk 1]
```diff
@@ -209,10 +209,7 @@ impl CallGraph {
             }
         }
 
-        let has_cycle = graph
-            .nodes
-            .iter()
-            .any(|(n, out_edges)| output.contains(n) && !out_edges.is_empty());
+        let has_cycle = output.len() != graph.nodes.len();
```
Comment (huitseeker) [inline crates/assembly/src/linker/callgraph.rs]: This invariant looks right, but I do not see a `toposort_caller` regression test for the case where a reachable cycle keeps some nodes from ever entering `output`. Could we add one here? The current tests cover the acyclic path and `toposort()`, but not this branch.

File: CHANGELOG.md [hunk 2]
```diff
@@ -33,6 +33,8 @@
 - [BREAKING] Enum types are now exported from libraries as a `midenc_hir_type::EnumType`, rather than the type of the discriminant. ([#2848](https://github.com/0xMiden/miden-vm/pull/2848))
 
 #### Fixes
+- **toposort_caller**: Fixed cycle detection in assembly call graph ([#2871](https://github.com/0xMiden/miden-vm/pull/2871)).
```
Comment (huitseeker) [inline CHANGELOG.md:41]: This looks like it inserted the same entry twice into every historical `#### Fixes` section, not just the current release block. Please fix.

**Comment by crazywriter1** [comment]
Addressed both review comments:
- Added regression test for toposort_caller with a reachable cycle
- Fixed CHANGELOG to only have the entry in the current release section
@huitseeker

File: crates/assembly/src/linker/callgraph.rs (hunk 1 above)
Comment (huitseeker) [inline crates/assembly/src/linker/callgraph.rs]: This new invariant fixes the downstream-cycle case, but I think `toposort_caller(A2)` on `callgraph_cycle()` still returns `Ok(...)`. We still drop every edge into `caller` a few lines above, so the backedge `A3 -> A2` gets erased before this check runs. 

Could we add a regression for a cycle that closes back into the root, or keep that edge visible to cycle detection?

File: crates/assembly/src/linker/callgraph.rs [hunk 3]
```diff
@@ -326,6 +323,21 @@ mod tests {
         assert_eq!(err.0.into_iter().collect::<Vec<_>>(), &[A2, A3, B2, B3]);
     }
 
+    #[test]
+    fn callgraph_toposort_caller_with_reachable_cycle() {
```
Comment (huitseeker) [inline crates/assembly/src/linker/callgraph.rs:360]: Could we make this test cover the root-closing case too, like `callgraph_cycle().toposort_caller(A2).expect_err(...)`? 

That is the case still [missed today that I was commenting on above](https://github.com/0xMiden/miden-vm/pull/2871/changes#r2973733098): `retain(|n| *n != caller)` removes the `A3 -> A2` backedge before `has_cycle` runs. A simple fix would be to record whether the reachable subgraph had any edge into `caller` before that `retain`, then use that flag together with `output.len() != graph.nodes.len()` when deciding if a cycle exists.

**Comment by crazywriter1** [comment]
Thanks for the detailed feedback sir. Added root closing cycle detection: recording edges into `caller` before `retain` and using that flag in `has_cycle`. Also added regression test for `toposort_caller(A2)` on the cycle graph. @huitseeker

File: CHANGELOG.md [hunk 4]
```diff
@@ -37,7 +37,7 @@
 - In `ExecutionTracer`, we no longer record node flags in `CoreTraceFragmentContext` when entering a node (they are redundant) ([#2866](https://github.com/0xMiden/miden-vm/pull/2866))
 
 #### Fixes
-- Fixed C-like enum validation and constant materialization in `define_enum` ([#2887](https://github.com/0xMiden/miden-vm/pull/2887)).
+- **toposort_caller**: Fixed cycle detection in assembly call graph ([#2871](https://github.com/0xMiden/miden-vm/pull/2871)).
```
Comment (huitseeker) [inline CHANGELOG.md:41]: I think this line accidentally replaces the `#2887` changelog item instead of adding `#2871` next to it. Since `#2887` is already merged into `next`, this drops that fix from the release notes. Can we keep both entries here?

Comment (crazywriter1) [reply CHANGELOG.md:41]: It already was like that but it caused a conflict. I'm fixing it now, sorry.

**Comment by crazywriter1** [comment]
Restored the #2887 changelog entry. Both fixes are now listed under the same section. Sorry about that. @huitseeker

File: crates/assembly/src/linker/callgraph.rs [hunk 5]
```diff
@@ -222,6 +228,10 @@ impl CallGraph {
                 in_cycle.insert(*n);
                 in_cycle.extend(edges.as_slice());
             }
+            if has_edge_to_caller {
+                in_cycle.insert(caller);
+                in_cycle.extend(caller_predecessors.iter());
```
Comment (huitseeker) [inline crates/assembly/src/linker/callgraph.rs]: This still drops part of the cycle in the root-closing case. For `A2 -> B2 -> B3 -> A3 -> A2`, this branch only rebuilds `{A2, A3}` after the traversal has already erased `B2` and `B3`'s outgoing edges, so the linker error hides two recursive procedures. 

We should derive cycle members from the original reachable subgraph.

**Review by bitwalker — APPROVED** [review]
