### PR TITLE
fix: assert instruction print bug

### LINKED ISSUE #1882: Assert instructions with errors print messages without quotes
When calling `to_string` on the family of assert instructions with an error message, e.g. `AssertWithError`, it currently prints something like: `assert.err=error message`, while I would expect it to print `assert.err="error message"`, i.e. with quotes.

I think the issue can be fixed by changing the `PrettyPrint` implementation:

https://github.com/0xMiden/miden-vm/blob/56c4ef18638348da0318cb1b325c7c81d17e9ff3/assembly/src/ast/instruction/print.rs#L15-L17

Mostly unrelated, but the `ErrorMsg` type alias is not exported like the other `ImmXyz` type aliases, so I assume it is an oversight. That be a nice to have and could be added here:

https://github.com/0xMiden/miden-vm/blob/56c4ef18638348da0318cb1b325c7c81d17e9ff3/assembly/src/ast/mod.rs#L30

### PR DESCRIPTION
**Pull request by varun-doshi**
## Describe your changes

Fixes #1882 
## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Commits are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.
- Updated `CHANGELOG.md'

### CODE REVIEW

File: assembly/src/ast/instruction/print.rs [hunk 1]
```diff
@@ -12,9 +12,9 @@ impl PrettyPrint for Instruction {
         match self {
             Self::Nop => const_text("nop"),
             Self::Assert => const_text("assert"),
-            Self::AssertWithError(err_code) => {
-                flatten(const_text("assert.err") + const_text("=") + display(err_code))
```
Comment (plafer) [inline assembly/src/ast/instruction/print.rs:16]: Looks good - except could you apply this same fix to all other variants that use `display()` like this?

That + fixing the CI and we should be good to merge

Comment (varun-doshi) [reply assembly/src/ast/instruction/print.rs:16]: Will do
