### PR TITLE
Fix diagnostics when external node resolution fails

### LINKED ISSUE #2476: Re-enable diagnostic tests after `FastProcessor` migration
With #2477, the following tests were disabled:

- `test_diagnostic_no_mast_forest_with_procedure()`
- `test_diagnostic_syscall_target_not_in_kernel()`

This comes after migrating them from `Process` to `FastProcessor`, only to realize that the `FastProcessor` didn't output proper diagnostics for both. The `Process`'s solution to use [`add_error_ctx_to_external_error()`](https://github.com/0xMiden/miden-vm/blob/f9fb1be9e03d7db7b0f5e2c9c066ff8c7ae009b4/processor/src/lib.rs#L1017-L1045) doesn't work with the `FastProcessor`, since the `FastProcessor` uses iterative execution instead of recursive execution (and hence can't "catch" the error generated by `execute_external_node()`, and enhance it with an `ErrorContext`). Further investigation is needed to make this work with the `FastProcessor`.

### PR DESCRIPTION
**Pull request by plafer**
Closes #2476 

Re-enables the 2 tests referenced in #2476, and fixes the expected digests (due to #2547). More specifically,

- `test_diagnostic_syscall_target_not_in_kernel()`: no solution needed, the error context set up in `start_call_node()` already correctly points to the syscall `CallNode`.
- `test_diagnostic_no_mast_forest_with_procedure()`: on error, we walk up one node in the continuation stack to find the caller of the `ExternalNode`, and wse the caller's node ID to build the error context (e.g. to get the diagnostic for the `CallNode`, no the `ExternalNode`). More information can be found in the docstring of the new `maybe_use_caller_error_context()` method.

I didn't add a changelog entry, since this bug was introduced in #2477, which will land in the same release.

### CODE REVIEW

File: processor/src/fast/external.rs [hunk 1]
```diff
@@ -86,3 +88,67 @@ impl FastProcessor {
...
+    }
+
+    // Look for caller context in the continuation stack
+    let Some(top_continuation) = continuation_stack.peek_continuation() else {
+        return original_err;
+    };
+
+    // Extract parent node ID from Call or Dyn continuations
+    let parent_node_id = match top_continuation {
+        Continuation::FinishCall(parent_node_id) | Continuation::FinishDyn(parent_node_id) => {
```
Comment (huitseeker) [inline processor/src/fast/external.rs]: nit: Could add a test that triggers `NoMastForestWithProcedure` via `dyncall` to cover the `FinishDyn` branch here?

**Review by huitseeker — APPROVED** [review]
This LGTM.

File: processor/src/fast/external.rs (hunk 1 above)
Comment (plafer) [reply processor/src/fast/external.rs]: Good catch, this made me realize that we don't use `ExternalNode` with `DynNode`s, since `DynNode`s get the digest to be executed on the stack. `ExternalNode` is only needed for `CallNode`, since it encodes the callee using a `MastNodeId`. Hence, I removed the `FinishDyn` case.

Though this made me double-check whether we should look for other parents (which we didn't do the first time with `Process`). Turns out we were missing a bunch of cases. We weren't catching when this happened in a join, split, or loop. Turns out the assembler doesn't generate `AssemblyOp` decorators for `JoinNode`s (though I still made us look for it in `maybe_use_caller_error_context()`) - I will create an issue for this.

So TLDR, diagnostics should now be better than they were with `Process` because of this - good catch 🙂

Comment (plafer) [reply processor/src/fast/external.rs]: Created #2594
