### PR TITLE
fix: replace deprecated #[clap(...)] with #[command(...)] and #[arg(.…)]

### LINKED ISSUE #1793: Deprecated #[clap(...)] attributes causing warnings/errors
### Feature description

In **clap** version 4.x and above, the use of `#[clap(...)]` is no longer valid.  
Many instances of `#[clap(...)]` are still present in the project.  
These should be replaced with `#[arg(...)]` or `#[command(...)]`.

### Why is this feature needed?

_No response_

### PR DESCRIPTION
**Pull request by Himess**
Closes #1793

### CODE REVIEW

File: miden/src/cli/bundle.rs [hunk 1]
```diff
@@ -14,24 +14,24 @@ use stdlib::StdLibrary;
 )]
 pub struct BundleCmd {
     /// Disable debug symbols (release mode)
-    #[clap(short = 'r', long = "release")]
+    #[arg(short = 'r', long = "release")]
     release: bool,
     /// Path to a directory containing the `.masm` files which are part of the library.
     #[clap(value_parser)]
```
Comment (plafer) [inline miden/src/cli/bundle.rs:20]:
```suggestion
    #[arg(value_parser)]
```

**Review by plafer — CHANGES_REQUESTED** [review]
Good idea! However, searching for `#[clap(` across the repo shows that there are still ~15 cases that still need to be changed (I added one as an example).
