### PR TITLE
fix `debug.local` panic and incorrect value printing

### LINKED ISSUE #1853: `debug.local` family of instructions are broken
### Packages versions

miden-assembly: 0.15.0 e67f956e474ff717941f5085f4850563192ad64f

### `debug.local`

The instruction to debug-print all local values, [`debug.local`](https://github.com/0xMiden/miden-vm/blob/2c2fc1fdc5db6334c3b56176a2985f8b028c6983/docs/src/user_docs/assembly/debugging.md?plain=1#L10), is effectively unimplemented. The following trivial Miden program attempts to print all locals with `debug.local`:

```asm
proc.main.1
	push.0x80
	loc_store.0
	debug.local
end

begin
	call.main
end
```

Instead of printing any local values, it panics with the rather confusing error message "unresolved constant".

```
Error:   x Main thread panicked.
  |-> at assembly/src/assembler/instruction/mod.rs:493:52
  `-> unresolved constant: ()
  help: set the `RUST_BACKTRACE=1` environment variable to display a
        backtrace.
```

The confusing "unresolved constant" message is from `miden_assembly::Assembler::compile_instruction_impl()`, which compiles the AST debug instruction with `<miden_core::DebugOptions as TryFrom<miden_assembly::ast::DebugOptions>>::try_from()`, and assumes a failure indicates a constant failing to resolve: <https://github.com/0xMiden/miden-vm/blob/2c2fc1fdc5db6334c3b56176a2985f8b028c6983/assembly/src/assembler/instruction/mod.rs#L490-L496>

The error case comes from a catch-all pattern returning `Err` in that `try_from()` implementation: <https://github.com/0xMiden/miden-vm/blob/2c2fc1fdc5db6334c3b56176a2985f8b028c6983/assembly/src/ast/instruction/debug.rs#L30-L46>

I assume this catch-all pattern is intended to catch `miden_assembly::ast::Immediate::Constant` variants for the `ImmU8`/`ImmU16`/`ImmU32` values, but it also catches `ast::DebugOptions::LocalRangeFrom` and `ast::DebugOptions::LocalAll`. Since `LocalAll` is what `debug.local` is parsed to, this instruction is uncompilable: <https://github.com/0xMiden/miden-vm/blob/2c2fc1fdc5db6334c3b56176a2985f8b028c6983/assembly/src/parser/grammar.lalrpop#L740-L746>

### `debug.local.<n>` and `debug.local.<n>.<m>`

The instruction to debug-print any single local value, [`debug.local.<n>`](https://github.com/0xMiden/miden-vm/blob/2c2fc1fdc5db6334c3b56176a2985f8b028c6983/docs/src/user_docs/assembly/debugging.md?plain=1#L11), compiles but does not work at all. The following trivial Miden program attempts to print a single local value with `debug.local.<n>`:

```asm
proc.main.1
	push.0x80
	loc_store.0
	debug.local.0
end

begin
	call.main
end
```

This program runs without crashing, but indicates that local memory is entirely empty, which is obviously wrong:

```
State of procedure local at index 0 before step 9:
└──     0: EMPTY
```

It is also not simply an offset error, as `debug.local.1`, `debug.local.2`, etc (which are allowed, even with `main` being declared with only 1 local) all continue to print `EMPTY`. Where things get interesting is what happens if we use the range version of `debug.local`:

```asm
proc.main.1
	push.0x80
	loc_store.0
	debug.local.0.2
end

begin
	call.main
end
```

```
State of procedure locals [0, 2] before step 9:
├──     0: 128
├──     1: EMPTY
└──     2: EMPTY
```

It turns out that with 1 local, any `n` and `m` where `m = 2n + 2` will print out `128` at the top. If the procedure has 2 locals, then it's `m = 2n + 3`, 3 locals is `2n + 4`, and so on.

`locaddr.<i>` *does* work correctly, and indeed the two calculate the locations of local memory differently:

- `debug.local` infers the number of procedure locals from its range: <https://github.com/0xMiden/miden-vm/blob/2c2fc1fdc5db6334c3b56176a2985f8b028c6983/assembly/src/ast/instruction/debug.rs#L38-L42>
- `locaddr.<i>` uses the number declared in the procedure from its context: <https://github.com/0xMiden/miden-vm/blob/af438c5db74653712e836bb27fbd51127f0bab1b/assembly/src/assembler/instruction/env_ops.rs#L42-L48>

### How can this be reproduced?

1. Create a Miden assembly file `debug-local.masm`:

```asm
proc.main.3
	push.0
	loc_store.0
	push.1
	loc_store.1
	push.2
	loc_store.2

	# Prints EMPTY.
	debug.local.0
	# Prints EMPTY.
	debug.local.1

	# Prints [2, EMPTY, EMPTY].
	debug.local.0.2

	# Panics
	debug.local

	dropw
end

begin
	call.main
end
```

2. Run the program with `cargo run -p miden-vm --bin=miden --features executable -- run ./debug-local.masm`
3. Observe the crash from `debug.local`
4. Comment out the bare `debug.local` instruction, and run the program again
5. Observe the incorrect local values printed out

### Relevant log output

```shell
Error:   x Main thread panicked.
  |-> at assembly/src/assembler/instruction/mod.rs:493:52
  `-> unresolved constant: ()
         0: 0x55555704826d - __rustc[8abf7dcf45103d39]::rust_begin_unwind
                      at /rustc/5d707b07e42766c080c5012869c9988a18dcbb83/
      library/std/src/panicking.rs:697
         1: 0x555557069630 - core::panicking::panic_fmt::h69df97bc566577cd
                      at /rustc/5d707b07e42766c080c5012869c9988a18dcbb83/
      library/core/src/panicking.rs:75
         2: 0x555557069a96 - core::result::unwrap_failed::h2891c1d607396171
                      at /rustc/5d707b07e42766c080c5012869c9988a18dcbb83/
      library/core/src/result.rs:1761
         3: 0x555556869014 -
      core::result::Result<T,E>::expect::hd6aee8fed0dab581
                      at /nix/store/jz21bw0pb5rdb6f27lb39ij5wnw9cd9s-rust-
      nightly-latest-2025-06-03/lib/rustlib/src/rust/library/core/src/
      result.rs:1119
         4: 0x55555685333d - miden_assembly::assembler::instruction::<impl
      miden_assembly::assembler::Assembler>::compile_instruction_impl::h3bf949
      ed810c3b6a
                      at /home/qyriad/code/miden/miden-vm/assembly/src/
      assembler/instruction/mod.rs:493
         5: 0x55555684d6c8 - miden_assembly::assembler::instruction::<impl
      miden_assembly::assembler::Assembler>::compile_instruction::h3e7e551941e
      68d55
                      at /home/qyriad/code/miden/miden-vm/assembly/src/
      assembler/instruction/mod.rs:32
         6: 0x55555682a73f -
      miden_assembly::assembler::Assembler::compile_body::h63f2a4b3ed026ba5
                      at /home/qyriad/code/miden/miden-vm/assembly/src/
      assembler/mod.rs:618
         7: 0x5555568556a5 -
      miden_assembly::assembler::Assembler::compile_procedure::h0e6435bd44da00
      28
                      at /home/qyriad/code/miden/miden-vm/assembly/src/
      assembler/mod.rs:588
         8: 0x5555568543fc -
      miden_assembly::assembler::Assembler::process_graph_worklist::h49a77ea10
      10f7331
                      at /home/qyriad/code/miden/miden-vm/assembly/src/
      assembler/mod.rs:516
         9: 0x555556853cf3 -
      miden_assembly::assembler::Assembler::compile_subgraph::ha6d09904b3c091c
      3
                      at /home/qyriad/code/miden/miden-vm/assembly/src/
      assembler/mod.rs:471
        10: 0x555555c1f80b -
      miden_assembly::assembler::Assembler::assemble_program::hb120d84724b1793
      a
                      at /home/qyriad/code/miden/miden-vm/assembly/src/
      assembler/mod.rs:426
        11: 0x555555c60411 -
      miden::cli::data::ProgramFile::compile::h72ee9474ab5c4e5a
                      at /home/qyriad/code/miden/miden-vm/miden/src/cli/
      data.rs:156
        12: 0x555555c050fa -
      miden::cli::utils::get_masm_program::h15f9df9252aa0515
                      at /home/qyriad/code/miden/miden-vm/miden/src/cli/
      utils.rs:36
        13: 0x555555c8ed1d -
      miden::cli::run::run_masm_program::h79c1c1374b36f7ff
                      at /home/qyriad/code/miden/miden-vm/miden/src/cli/
      run.rs:175
        14: 0x555555c89a8b -
      miden::cli::run::RunCmd::execute::h52a0e7acb0921af0
                      at /home/qyriad/code/miden/miden-vm/miden/src/cli/
      run.rs:77
        15: 0x555555eb38b1 - miden::Cli::execute::he0fa8d243637bb5a
                      at /home/qyriad/code/miden/miden-vm/miden/src/main.rs:46
        16: 0x555555eb3bdc - miden::main::hd866ac07c1ee4c1f
                      at /home/qyriad/code/miden/miden-vm/miden/src/main.rs:86
        17: 0x555555d0b38b -
      core::ops::function::FnOnce::call_once::hc97989dd3dae729a
                      at /nix/store/jz21bw0pb5rdb6f27lb39ij5wnw9cd9s-rust-
      nightly-latest-2025-06-03/lib/rustlib/src/rust/library/core/src/ops/
      function.rs:250
```

### PR DESCRIPTION
**Pull request by Qyriad**
## Describe your changes

The compilation of `ast::DebugOptions` was slightly refactored to accommodate these fixes, but bare `debug.local` no longer panics and instead prints all local values, and the other two variants now print from the correct part of memory.

I considered adding tests for this, but currently most of the heavy lifting is also done in the functions that do the actual printing.

Fixes #1853.

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Commits are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.
- Updated `CHANGELOG.md'

### CODE REVIEW

File: assembly/src/ast/instruction/debug.rs [hunk 1]
```diff
@@ -18,31 +22,45 @@ pub enum DebugOptions {
...
+        type Vm = vm_core::DebugOptions;
 
-    fn try_from(options: DebugOptions) -> Result<Self, Self::Error> {
-        match options {
-            DebugOptions::StackAll => Ok(Self::StackAll),
-            DebugOptions::StackTop(ImmU8::Value(n)) => Ok(Self::StackTop(n.into_inner())),
-            DebugOptions::MemAll => Ok(Self::MemAll),
-            DebugOptions::MemInterval(ImmU32::Value(start), ImmU32::Value(end)) => {
-                Ok(Self::MemInterval(start.into_inner(), end.into_inner()))
+        let compiled = match self {
```
Comment (plafer) [inline assembly/src/ast/instruction/debug.rs]: Let's add a comment for why it's safe to use `expect_value()` here. IIUC, this is because in semantic analysis, all `Immediate::Constant` are converted to `Immediate::Value`

File: processor/src/host/debug.rs [hunk 2]
```diff
@@ -141,33 +141,38 @@ impl Printer {
...
-        let local_memory_offset = self.fmp - num_locals + 1;
-
-        // in case start index is 0 and end index is 2^16, we should print all available locals.
-        let (start, end) = if interval.0 == 0 && interval.1 == u16::MAX as u32 {
+    ///
+    /// The interval given is inclusive on *both* ends.
+    fn print_local_interval(
+        &self,
+        process: ProcessState,
+        (start, end): (u32, u32),
```
Comment (plafer) [inline processor/src/host/debug.rs]: I see that this keeps the same style as before, but let's split these into separate function arguments

File: processor/src/host/debug.rs [hunk 3]
```diff
@@ -141,33 +141,38 @@ impl Printer {
...
-            println!("State of procedure locals before step {}:", self.clk)
-        } else if interval.0 == interval.1 {
-            println!("State of procedure local at index {} before step {}:", interval.0, self.clk,)
-        } else {
-            println!(
-                "State of procedure locals [{}, {}] before step {}:",
-                interval.0, interval.1, self.clk,
-            )
-        };
+        let locals: Vec<(u32, Option<Felt>)> = (start..=end)
```
Comment (plafer) [inline processor/src/host/debug.rs:158]: We currently print 1 extra local, e.g.

```
proc.main.1
	push.0x80
	loc_store.0
	debug.local
end

begin
	call.main
end
```
prints 

```
State of procedure locals [0, 1] before step 9:
├──     0: 128
└──     1: EMPTY
```

We'd basically want `State of procedure local 0 before step X`, and only printing index `0`

File: assembly/src/ast/instruction/debug.rs (hunk 1 above)
Comment (Qyriad) [reply assembly/src/ast/instruction/debug.rs]: That's correct, though note that these panics were already present beforehand, just implicit: https://github.com/0xMiden/miden-vm/blob/34f195de2bba4a3250a6f8b23c19e7a22d6648a5/assembly/src/assembler/instruction/mod.rs#L530-L536

Through semantic analysis I *think* it should be not be possible for constants to be unresolved here, but I cannot be sure, so I preserved the same assumptions and panic-conditions as the existing code (albeit more explicit).

File: processor/src/host/debug.rs (hunk 3 above)
Comment (Qyriad) [reply processor/src/host/debug.rs:158]: Fixed!

**Comment by Qyriad** [comment]
Comments addressed and rebased against next.

File: processor/src/host/debug.rs (hunk 3 above)
Comment (plafer) [reply processor/src/host/debug.rs:158]: This example still prints the `1: EMPTY`; haven't checked the code but there's most likely another edge case somewhere that's not handled properly. Basically to reproduce,

1. `cd` into the `miden/` subdirectory
2. create a `test.masm` file with the above contents
3. execute `cargo run --features executable -- run test.masm`

I double-checked that I was running the latest commit ([2db9a29](https://github.com/0xMiden/miden-vm/pull/1859/commits/2db9a29735697fd878060937f79669e4a64ba8b3)) too

Comment (Qyriad) [reply processor/src/host/debug.rs:158]: Ah! I missed a push! That should be fixed for real now.

**Review by plafer — APPROVED** [review]
LGTM thank you!
