### PR TITLE
Fix `u32` overflow in ACE circuit evaluation

### LINKED ISSUE #1820: [SECURITY] CircuitEvaluation::new(): Add overflow
### Packages versions

miden-vm:0.15.0

### Bug description

Our team at [FuzzingLabs](https://github.com/FuzzingLabs) discovered an overflow in `CircuitEvaluation::new()` event.

## Context

The `eval_circuit` function is part of Miden VM’s ACE chiplet, which lets the VM verify arithmetic circuits encoded directly in its memory. It first reads a sequence of quadratic‐extension inputs (`READ` segment) and then a series of base‐field–encoded gate instructions (`EVAL` segment), builds an internal graph via `CircuitEvaluation`, and finally checks that the circuit’s output is zero. The `CircuitEvaluation::new` constructor simply reserves the right amount of space for wires and gates based on the provided counts.

## Root cause

```rust
impl CircuitEvaluation {
    /// Generates the nodes in the graph generated by evaluating the inputs and circuit
    /// located in a contiguous memory region.
    pub fn new(ctx: ContextId, clk: RowIndex, num_read_rows: u32, num_eval_rows: u32) -> Self {
        let num_wires = 2 * num_read_rows + num_eval_rows; <-- ADD Overflow here
        let num_rows = num_read_rows + num_eval_rows;

        Self {
            ctx,
            clk,
            wire_bus: WireBus::new(num_wires),
            col_ptr: Vec::with_capacity(num_rows as usize),
            col_op: Vec::with_capacity(num_eval_rows as usize),
            col_wire_out: WireColumn::new(num_rows as usize),
            col_wire_left: WireColumn::new(num_rows as usize),
            col_wire_right: WireColumn::new(num_eval_rows as usize),
            num_read_rows,
            num_eval_rows,
        }
    }
    ...
```

The panic occurs because the expression

```rust

let num_wires = 2 * num_read_rows + num_eval_rows;
```

is computed in plain 32-bit unsigned arithmetic. When `num_read_rows` is large enough that doubling it exceeds `u32::MAX`

## Impact

- **In debug builds**, Rust checks for overflow in integer arithmetic and will panic immediately on `2 * num_read_rows` if the product doesn’t fit in 32 bits.
- **In release builds**, overflow in `u32` arithmetic silently wraps modulo 2³², so `num_wires` ends up with an incorrect, wrapped‐around value.

This discrepancy means that a program which crashes under debug can instead proceed with a bogus `num_wires` in release, leading to data structures being mis‐sized and subsequent operations behaving non-deterministically.

## Step to reproduce

Payload:

```rust

Raw:040403040404313f5d

incr
incr
inv
incr
incr
incr
dup0
clk
arithmetic_circuit_eval
```

Stack Input:

```rust

StackInputs::default()
```

Test code

```rust

#[cfg(test)]
mod runner_tests {
    use std::sync::Arc;
    use miden_core::mast::{MastForest, MastNodeId};
    use miden_vm::assembly::ast::Op;
    use miden_vm::{Operation, Program, execute, StackInputs, DefaultHost};
    use miden_vm::diagnostics::DefaultSourceManager;
    use miden_air::ExecutionOptions;

    #[test]
    fn circuit_evaluation_add_overflow_test() {
        
        let ops = vec![
            Operation::Incr,
            Operation::Incr,
            Operation::Inv,
            Operation::Incr,
            Operation::Incr,
            Operation::Incr,
            Operation::Dup0,
            Operation::Clk,
            Operation::ArithmeticCircuitEval,
        ];

        let mut forest = MastForest::new();
        let block_id: MastNodeId = forest
            .add_block(ops, None)
            .expect("add_block should work");
        forest.make_root(block_id);

        let program = Program::new(Arc::new(forest), block_id);
        let inputs      = StackInputs::default();
        let mut host    = DefaultHost::default();
        let opts        = ExecutionOptions::default();
        let src_manager = Arc::new(DefaultSourceManager::default());

        let result = execute(&program, inputs, &mut host, opts, src_manager);
        assert!(result.is_ok(), "the VM should execute without error");
    }
}

```

## Backtrace

```rust
thread 'main' panicked at /Users/lxt3h/.cargo/git/checkouts/miden-vm-119bb9de8325aa8d/f6297e1/processor/src/chiplets/ace/trace.rs:50:25:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/std/src/panicking.rs:695:5
   1: core::panicking::panic_fmt
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_const::panic_const_add_overflow
             at /rustc/05f9846f893b09a1be1fc8560e33fc3c815cfecb/library/core/src/panicking.rs:178:21
   3: miden_processor::chiplets::ace::trace::CircuitEvaluation::new
             at /Users/lxt3h/.cargo/git/checkouts/miden-vm-119bb9de8325aa8d/f6297e1/processor/src/chiplets/ace/trace.rs:50:25
   4: miden_processor::chiplets::ace::eval_circuit

```

### How can this be reproduced?

_No response_

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by adr1anh**
## Describe your changes

Fixes #1820

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](./CONTRIBUTING.md).
- Commits are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.
- Updated `CHANGELOG.md'

### CODE REVIEW

File: processor/src/chiplets/ace/mod.rs [hunk 1]
```diff
@@ -24,6 +24,7 @@ mod tests;
 
 pub const PTR_OFFSET_ELEM: Felt = Felt::ONE;
 pub const PTR_OFFSET_WORD: Felt = Felt::new(4);
+pub const MAX_ACE_WIRES: u32 = instruction::MAX_ID;
```
Comment (Al-Kindi-0) [inline processor/src/chiplets/ace/mod.rs:27]: maybe `MAX_NUM_ACE_WIRES` or something similar?

File: processor/src/chiplets/ace/trace.rs [hunk 2]
```diff
@@ -47,13 +51,15 @@ impl CircuitEvaluation {
...
+        let num_wires = 2 * (num_read_rows as u64) + (num_eval_rows as u64);
+        assert!(num_wires <= MAX_ACE_WIRES as u64, "too many wires");
+
         let num_rows = num_read_rows + num_eval_rows;
 
         Self {
             ctx,
             clk,
-            wire_bus: WireBus::new(num_wires),
+            wire_bus: WireBus::new(num_wires as u32),
```
Comment (Al-Kindi-0) [inline processor/src/chiplets/ace/trace.rs:62]: Question: would it also make sense to check that it is safely castable as a u32?

**Review by Al-Kindi-0 — APPROVED** [review]
Looks good!

File: processor/src/chiplets/ace/trace.rs (hunk 2 above)
Comment (adr1anh) [reply processor/src/chiplets/ace/trace.rs:62]: The maximum is 2^30 so casting is always safe.
