### PR TITLE
Fix EXT2 ops docs

### LINKED ISSUE #2179: Docs: Fix notes for `ext2mul` instruction documentation
Hi! In the documentation page for field operations, the formula for the `c1` term of the `ext2mul` instruction should probably include the term `- a0 * b0` (or be expanded into `a0 * b1 + a1 * b0 + a1 * b1`).

Pages affected:
- https://0xmiden.github.io/miden-vm/user_docs/assembly/field_operations.html#extension-field-operations
- https://0xmiden.github.io/miden-vm/user_docs/assembly/instruction_reference.html#extension-field-operations

### PR DESCRIPTION
**Pull request by Al-Kindi-0**
## Describe your changes
Specifies the irreducible polynomial used to define our quadratic extension field.

Closes #2179

## Checklist before requesting a review
- Repo forked and branch created from `next` according to naming convention.
- Commit messages and codestyle follow [conventions](../CONTRIBUTING.md).
- Commits are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- Relevant issues are linked in the PR description.
- Tests added for new functionality.
- Documentation/comments updated according to changes.
- Updated `CHANGELOG.md'

### CODE REVIEW

File: air/src/constraints/stack/field_ops/mod.rs [hunk 1]
```diff
@@ -381,7 +381,24 @@ pub fn enforce_expacc_constraints<E: FieldElement>(
...
+/// Since x² ≡ x - 2 in 𝔽ₚ[x]/(x² - x + 2), this reduces to:
+///
+///     a · b = (a1·b0 + a0·b1 + a1·b1)·x + (a0·b0 - 2·a1·b1).
+///
+/// The formula for the x coefficient can be implemented more efficiently using the Karatsuba
+/// trick, namely
+///
+/// a1·b0 + a0·b1 + a1·b1 = (b0 + b1)(a0 + a1) - b0·a0
+///
+/// which reduces the number of multiplications at the expense of one subtraction.
```
Comment (huitseeker) [inline air/src/constraints/stack/field_ops/mod.rs:406]: I would have name-dropped Karatsuba since the algorithm is so famous.

**Review by huitseeker — APPROVED** [review]
Thanks a lot for cleaning this up @Al-Kindi-0 🙏 . There's a few CI issues that may require a touch-up from a rustdoc PoV.


I took the liberty of mentioning the issue in the PR summary.

File: air/src/constraints/stack/field_ops/mod.rs (hunk 1 above)
Comment (Al-Kindi-0) [reply air/src/constraints/stack/field_ops/mod.rs:406]: I did, on line 395 above

**Comment by Al-Kindi-0** [comment]
> [...] There's a few CI issues that may require a touch-up from a rustdoc PoV.

I fixed some formatting issues and things are green on my local machine. Strangely, this didn't change their state in the CI and I am not sure why.

**Comment by bobbinth** [comment]
> Strangely, this didn't change their state in the CI and I am not sure why.

Yeah - CI seems to be broken, and I'm not sure why myself. As far as I can tell, it's not something we did - but I haven't had a chance to investigate further yet.

**Comment by Al-Kindi-0** [comment]
> > Strangely, this didn't change their state in the CI and I am not sure why.
> 
> Yeah - CI seems to be broken, and I'm not sure why myself. As far as I can tell, it's not something we did - but I haven't had a chance to investigate further yet.

Thanks for confirming

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you!
