### PR TITLE
fix: replace ErrorContext

### LINKED ISSUE #1978: Investigate removing `ErrorContext`
See https://github.com/0xMiden/miden-vm/pull/1884#issuecomment-3056286215 and https://github.com/0xMiden/miden-vm/pull/1884#issuecomment-3058246443

### LINKED ISSUE #2517: Clean up `ExecutionError` enum
... we need to clean up `ExecutionError` enum and this module in general. A few examples:

- `CycleLimitExceeded` doesn't seems to be used - are we no longer enforcing upper limits on execution? This is important functionality that is used downstream (e.g., in `miden-node`).
- `UnexpectedPrecompiles`, `MastNodeNotFoundInForest`, `SmtNodePreImageNotValid`, `SmtNodeNotFound` and probably other variants are not used anywhere. Maybe some are obsolete - and then we should remove them. But it also may be possible that some of them need to be reenabled.
- `InvalidCryptoInput` is confusingly named. I think it should be much more operation-specific (this seems to be used specifically on Merkle root update instruction).
- How we instantiate enum variants is rather inconsistent - sometimes we use constructor functions, sometimes we do this directly. We should normalize the approach.
- Enum variants should be sorted alphabetically.

Let's create an issue for this.

_Originally posted by @bobbinth in https://github.com/0xMiden/miden-vm/pull/2472#discussion_r2654512033_

### PR DESCRIPTION
**Pull request by huitseeker**
Closes #1978. Fixes #2517.

This PR removes `ErrorContext` parameter threading from leaf methods in the processor. Previously, `err_ctx` was passed through many layers of function calls just to attach source location when an error occurred. Now, leaf methods return lightweight context-free errors, and source location is added once at execution boundaries.

Credit to @adr1anh for the initial design sketch in #1978 (and an initial branch too).

## Approach

**Before:** Every leaf operation took `err_ctx: &impl ErrorContext` and embedded source location directly in errors.

**After:** Leaf operations return context-free error enums (`OperationError`, `MemoryError`, etc.). Extension traits like `ResultExt::map_exec_err()` add source location at the call site.

```
                        BEFORE                              AFTER

    execute_op ──┬── err_ctx ──► op_div ──► error      execute_op ──► op_div ──► OperationError
                 │                  │                        │                         │
                 ├── err_ctx ──► op_and ──► error            └── .map_exec_err() ◄─────┘
                 │                  │                             (adds context)
                 └── err_ctx ──► op_inv ──► error
```

This reduces `err_ctx` parameter declarations from 106 to 19 (82% reduction). The remaining 19 are trait definitions and boundary functions where context should be added.

## Changes

**New error types:**
- `OperationError` - context-free errors for operations (div-by-zero, assertion failures, type mismatches)
- `IoError` - context-free errors for IO operations (advice + memory)
- `SystemEventError` - context-free errors for system event handlers
- `AceEvalError` - context-free errors for ACE circuit evaluation

**Extension traits for lazy context wrapping:**
- `OperationResultExt::map_exec_err()`
- `MemoryResultExt::map_mem_err()`
- `IoResultExt::map_io_err()`
- `SystemEventResultExt::map_sys_event_err()`
- `AceEvalResultExt::map_ace_eval_err()`

Each error type has its own extension trait because the mapping logic differs:
- `IoError::Execution` unwraps a boxed error rather than wrapping
- Some traits need `op_idx` for precise source location, others don't
- `AdviceResultExt` has a `_no_ctx` variant for context-free cases
- Variant counts differ (SystemEventError has 3, MemoryError has 1)

**Removed unused `ExecutionError` variants** (addresses #2517):
- `MastNodeNotFoundInForest`
- `SmtNodeNotFound`
- `SmtNodePreImageNotValid`
- `UnexpectedPrecompiles`

**Split `ExecutionError::MemoryError`** into two variants:
- `MemoryError { label, source_file, err }` - for user-facing errors with source context
- `MemoryErrorNoCtx(MemoryError)` - for internal operations without meaningful source context

## Review Guide

1. **Start with `processor/src/errors.rs`** - see the new error types and extension traits
2. **Check a leaf operation** like `processor/src/processor/operations/field_ops.rs` - note it returns `OperationError`, not `ExecutionError`
3. **Check a boundary** like `processor/src/processor/operations/mod.rs:execute_sync_op` - note it calls `.map_exec_err(err_ctx, clk)` to add context
4. **Integration tests** show pattern matching still works: `miden-vm/tests/integration/operations/field_ops.rs`

### CODE REVIEW

File: processor/src/errors.rs [hunk 1]
```diff
@@ -508,8 +587,12 @@ macro_rules! err_ctx {
...
 #[macro_export]
 macro_rules! err_ctx {
-    ($mast_forest:expr, $node:expr, $host:expr, $in_debug_mode:expr) => {{ () }};
-    ($mast_forest:expr, $node:expr, $host:expr, $in_debug_mode:expr, $op_idx:expr) => {{ () }};
+    ($mast_forest:expr, $node:expr, $host:expr, $in_debug_mode:expr) => {
+        ()
+    };
+    ($mast_forest:expr, $node:expr, $host:expr, $in_debug_mode:expr, $op_idx:expr) => {
+        ()
+    };
```
Comment (plafer) [inline processor/src/errors.rs]: I think we can get rid of the `err_ctx!` macro, the `no_err_ctx` feature and potentially `ErrorContext` altogether. The idea would be to run the `precalc_label_and_source_file()` function inside the `XResultExt::map_x_err()` methods.

For example, I would see `OperationResultExt<T>` being implemented as something like

```rs
impl<T> OperationResultExt<T> for Result<T, OperationError> {
    // The `mast_forest`, `node_id` and `host` are used to call today's
    // `ErrorContextImpl::precalc_label_and_source_file()` internally
    // (converted to a standalone function).
    fn map_exec_err(
        self,
        mast_forest: &MastForest,
        node_id: MastNodeId,
        host: &impl BaseHost,
        clk: AirRowIndex,
    ) -> Result<T, ExecutionError> {
        self.map_err(|err| {
            let (label, source_file) = calculate_label_and_source_file(mast_forest, node_id, host);
            ExecutionError::OperationError { label, source_file, clk, err }
        })
    }
}
```

The core idea being that since we now delay the label & source file lookup computation with a closure to be run only on error, we don't need any of the `ErrorContext`/`err_ctx!`/`no_err_ctx` machinery anymore.

**Comment by adr1anh** [comment]
I think we can also remove the `clk` since it's quite easy to get wrong, and doesn't provide much info in the failure case. Cc @plafer who suggested this.

**Comment by huitseeker** [comment]
@plafer @adr1anh Thanks for the bold but simplifying suggestions! Have a look at https://github.com/0xMiden/miden-vm/pull/2544/commits/36434b6f7c29c1c612a570d30df5bae87a4fc52c

File: processor/src/chiplets/memory/errors.rs [hunk 2]
```diff
@@ -34,34 +30,9 @@ pub enum MemoryError {
...
-        #[label("tried to access memory address {addr}")]
-        label: SourceSpan,
-        #[source_code]
-        source_file: Option<Arc<SourceFile>>,
-        addr: u32,
-        ctx: ContextId,
-        clk: Felt,
-    },
-    // Note: we need this version as well because to handle advice provider calls, which don't
+    UnalignedWordAccess { addr: u32, ctx: ContextId, clk: Felt },
```
Comment (adr1anh) [inline processor/src/chiplets/memory/errors.rs]: Does it make sense to remove the `clk` here and remove the `UnalignedWordAccessNoClk` variant? cc @plafer

File: processor/src/chiplets/bitwise/mod.rs [hunk 3]
```diff
@@ -124,14 +119,9 @@ impl Bitwise {
...
-    pub fn u32xor(
-        &mut self,
-        a: Felt,
-        b: Felt,
-        err_ctx: &impl ErrorContext,
-    ) -> Result<Felt, ExecutionError> {
-        let a = assert_u32(a, err_ctx)?.as_canonical_u64();
-        let b = assert_u32(b, err_ctx)?.as_canonical_u64();
+    pub fn u32xor(&mut self, a: Felt, b: Felt) -> Result<Felt, OperationError> {
+        let a = assert_u32(a)?.as_canonical_u64();
```
Comment (adr1anh) [inline processor/src/chiplets/bitwise/mod.rs:123]: Not for this PR, but it might make sense to return the resulting `u32` from `assert_u32`.

File: processor/src/chiplets/kernel_rom/mod.rs [hunk 4]
```diff
@@ -74,16 +74,12 @@ impl KernelRom {
...
-        proc_hash: Digest,
-        err_ctx: &impl ErrorContext,
-    ) -> Result<(), ExecutionError> {
+    pub fn access_proc(&mut self, proc_hash: Digest) -> Result<(), OperationError> {
         let proc_hash_bytes: ProcHashBytes = proc_hash.into();
         let access_info = self
             .access_map
             .get_mut(&proc_hash_bytes)
-            .ok_or(ExecutionError::syscall_target_not_in_kernel(proc_hash, err_ctx))?;
+            .ok_or(OperationError::SyscallTargetNotInKernel { proc_root: proc_hash })?;
```
Comment (adr1anh) [inline processor/src/chiplets/kernel_rom/mod.rs]: Should we rename `proc_hash` to `proc_root` for consistency (or the other way round)?

File: processor/src/chiplets/memory/errors.rs (hunk 2 above)
Comment (adr1anh) [inline processor/src/chiplets/memory/errors.rs]: Is `ctx` relevant for the error message?

File: processor/src/fast/tests/memory.rs [hunk 5]
```diff
@@ -32,10 +30,8 @@ fn test_memory_word_access_alignment() {
         let err = FastProcessor::new(&[43_u32.into()])
             .execute_sync(&program, &mut host)
             .unwrap_err();
-        assert_eq!(
-            err.to_string(),
-            "word memory access at address 43 in context 0 is unaligned at clock cycle 1"
-        );
+        // The error is wrapped: "memory error" is the outer message
+        assert_eq!(err.to_string(), "memory error");
```
Comment (adr1anh) [inline processor/src/fast/tests/memory.rs]: I think @plafer mentioned the "memory error" is not super useful to users, and we can avoid adding an extra error line by just transparently printing the inner memory error.

File: processor/src/fast/mod.rs [hunk 6]
```diff
@@ -835,35 +832,40 @@ impl FastProcessor {
...
 
         // Merge the advice map of this forest into the advice provider.
         // Note that the map may be merged multiple times if a different procedure from the same
         // forest is called.
         // For now, only compiled libraries contain non-empty advice maps, so for most cases,
         // this call will be cheap.
-        self.advice
-            .extend_map(mast_forest.advice_map())
-            .map_err(|err| ExecutionError::advice_error(err, self.clk, err_ctx))?;
+        self.advice.extend_map(mast_forest.advice_map()).map_advice_err(
```
Comment (adr1anh) [inline processor/src/fast/mod.rs]: This might warrant a special error type indicating that this is due to a malformed Mast. Not for this PR though.

File: processor/src/tests/mod.rs [hunk 7]
```diff
@@ -123,14 +125,16 @@ fn test_diagnostic_advice_map_key_not_found_2() {
 
     let build_test = build_test_by_mode!(true, source, &[1, 2]);
     let err = build_test.execute().expect_err("expected error");
+    // Note: The source location points to the first operation in the basic block because
+    // system event errors currently don't have access to the specific operation index.
```
Comment (adr1anh) [inline processor/src/tests/mod.rs:128]: Is it worth making an issue for this?

File: processor/src/chiplets/memory/errors.rs (hunk 2 above)
Comment (plafer) [reply processor/src/chiplets/memory/errors.rs]: That would be my preference yes, I don't think seeing "X occurred on clock cycle 5362" ever helped anyone

Comment (plafer) [reply processor/src/chiplets/memory/errors.rs]: Hmmm, my thoughts were that it would help the user distinguish between whether the error occurred in the kernel or user code. But I guess they'll see that from the diagnostics. So yeah, it's probably not that relevant?

**Comment by adr1anh** [comment]
This is great, and thank you for putting this together! There were a few things that I considered a while ago when I tackled this. I think many of these points can be tackled in later PRs though.

#### Stack size

Even with these changes, we end up with a pretty big stack footprint both due to the number of arguments we need to pass to functions, but also due to the growing size of `ExecutionError`. For the former, this could potentially be solved by re-introducing an `ErrorContext` struct that can be passed down as reference. For the latter, we could try to add more `Box`ing of inner types. It's not exactly trivial since `Diagnostic` is not implemented for `Box<DiagnosticError>` directly and can be a bit more awkward.

#### Review use of `help` messages

The current usages of `#[diagnostic(help(...)]` are few and don't add much info to the error. Except for [`AdviceError::MapKeyAlreadyPresent`](https://github.com/0xMiden/miden-vm/blob/cb5d74b08e336e154f911e201e938979e5c5137b/processor/src/host/advice/errors.rs#L16), the other messages could be replaced with a more exhaustive error string. We could even do the same for the latter. 

I think this would lead to simplifications since we can remove `#[diagnostic()]` and `#[diagnostic(transparent)]` attributes on `ExecutionError` variants, while also unifying error messages. Another benefit would be that it makes it easier to `Box` the inner error, helping with the above point.

#### Review actual error variants

I've noticed a couple of errors are only instantiated once or twice.

- `AceError` could probably be simplified to just be a `String` since most variants do not contain any information, and these internal errors are mostly useful for us. I think users would only really care that `"ace circuit evaluation failed"`.
- The same holds for FRI-related errors. 
- We could consolidate NotBinaryValue / NotBinaryValueIf / NotBinaryValueLoop
- DynamicNodeNotFound and NoMastForestWithProcedure are quite similar and I think the difference would be clear from the miette diagnostics (either pointing to a dynexec / dyncall or a procedure). We could make these a single ProcedureNotFound. Conceptually, they're probably more like ExecutionErrors than OperationErrors

We could also introduce a `HostError` for the DuplicateEventHandler / TraceHandlerError / DebugHandlerError / ReservedEventNamespace variants. 

#### Introduce Mast-specific error type

I'm not entirely sure if this makes sense, this is mainly motivated by the fact that a failure to merge a MastForest's AdviceMap returns an AdviceError in [`load_mast_forest`](https://github.com/0xMiden/miden-vm/blob/36434b6f7c29c1c612a570d30df5bae87a4fc52c/processor/src/fast/mod.rs#L835). I'm not sure whether this is actually more useful to users though, and could be tackled at the same time as lazy AdviceMap loading.

File: processor/src/chiplets/memory/errors.rs (hunk 2 above)
Comment (huitseeker) [reply processor/src/chiplets/memory/errors.rs]: Done!

File: processor/src/chiplets/kernel_rom/mod.rs (hunk 4 above)
Comment (huitseeker) [reply processor/src/chiplets/kernel_rom/mod.rs]: Done

File: processor/src/fast/tests/memory.rs (hunk 5 above)
Comment (huitseeker) [reply processor/src/fast/tests/memory.rs]: Done + commit rationalizing the error wrapping

**Comment by huitseeker** [comment]
Thanks for the thorough review @adr1anh! Really helpful suggestions.

On consolidating `NotBinaryValue` / `NotBinaryValueIf` / `NotBinaryValueLoop`: there's a tradeoff here. The miette diagnostics do point to the exact instruction (`if.true`, `while.true`, etc.), which makes the variant-specific messages somewhat redundant. But the explicit messages ("if statement expected...", "loop condition must be...") provide immediate context without requiring users to parse the source snippet. I'd lean toward keeping them separate for now, but happy to revisit.

  For the other suggestions not yet addressed, I think each warrants its own issue:

  - Stack size reduction (re-introduce `ErrorContext` as a reference struct, more `Box`ing of inner types)
  - Review `#[diagnostic(help(...))]` usage (most could be folded into error messages)
  - Consolidate error variants (`AceError` to `String`, FRI errors, `NotBinaryValue*` variants, `DynamicNodeNotFound`/`NoMastForestWithProcedure`)
  - Introduce `HostError` for handler-related variants
  - Mast-specific error type for `load_mast_forest` failures

  The core scope of this PR was addressing issue #1978: removing eager `ErrorContext computation`. That's done - we've removed the `ErrorContext` trait, `err_ctx!` macro, and `no_err_ctx` feature, replacing them with lazy context resolution via extension traits. I think this is ready for final review and merge, with the above as follow-up work.
  
  
  ----
  **Edit:** opened #2576, #2577, #2578 to track

File: processor/src/errors.rs [hunk 8]
```diff
@@ -261,332 +93,584 @@ pub enum ExecutionError {
...
+    node_id: MastNodeId,
+    host: &impl BaseHost,
+    in_debug_mode: bool,
+) -> (SourceSpan, Option<Arc<SourceFile>>) {
+    // When not in debug mode, skip the expensive decorator traversal entirely.
+    // Decorators (including AsmOp decorators used for error context) should only
+    // be accessed when debugging is enabled.
+    if !in_debug_mode {
+        return (SourceSpan::UNKNOWN, None);
     }
```
Comment (plafer) [inline processor/src/errors.rs]: Is this necessary, given that it's only done once and on error right before program exit? Also, I could see us wanting to generate proper diagnostics in production without necessarily running in debug mode. What do you think?

File: processor/src/errors.rs [hunk 9]
```diff
@@ -261,332 +93,584 @@ pub enum ExecutionError {
...
+    /// Maps an `OperationError` to an `ExecutionError` with op index context.
+    fn map_exec_err_with_op_idx(
+        self,
+        mast_forest: &MastForest,
+        node_id: MastNodeId,
+        host: &impl BaseHost,
+        in_debug_mode: bool,
+        op_idx: usize,
+    ) -> Result<T, ExecutionError>;
+}
```
Comment (plafer) [inline processor/src/errors.rs]: Any reason we want a new trait for every concrete error type? Couldn't we have 3 traits (one with `map_exec_err()`, one with `map_exec_err_with_op_idx()`, and one with `map_exec_err_no_ctx()`), and implement the appropriate one(s) for `Result<T, OperationError>`, `Result<T, AdviceError>`, etc? Something like (names subject to change)

```rs
// The traits - only showing the 2 main ones for simplicity

pub trait MapExecutionErrorExt<T> {
    /// Maps an error to an `ExecutionError` with the provided context.
    fn map_exec_err(
        self,
        mast_forest: &MastForest,
        node_id: MastNodeId,
        host: &impl BaseHost,
        in_debug_mode: bool,
    ) -> Result<T, ExecutionError>;
}

pub trait MapExecutionErrorWithOpIdxExt<T> {
    /// Maps an error to an `ExecutionError` with op index context.
    fn map_exec_err_with_op_idx(
        self,
        mast_forest: &MastForest,
        node_id: MastNodeId,
        host: &impl BaseHost,
        in_debug_mode: bool,
        op_idx: usize,
    ) -> Result<T, ExecutionError>;
}

// OperationError: implement both traits

impl<T> MapExecutionErrorExt<T> for Result<T, OperationError> {
    fn map_exec_err(
        self,
        mast_forest: &MastForest,
        node_id: MastNodeId,
        host: &impl BaseHost,
        in_debug_mode: bool,
    ) -> Result<T, ExecutionError> {
        // ...
    }
}

impl<T> MapExecutionErrorWithOpIdxExt<T> for Result<T, OperationError> {
    fn map_exec_err_with_op_idx(
        self,
        mast_forest: &MastForest,
        node_id: MastNodeId,
        host: &impl BaseHost,
        in_debug_mode: bool,
    ) -> Result<T, ExecutionError> {
        // ...
    }
}

// All other error types: only implement MapExecutionErrorExt

impl<T> MapExecutionErrorExt<T> for Result<T, AdviceError> {
    fn map_exec_err(
        self,
        mast_forest: &MastForest,
        node_id: MastNodeId,
        host: &impl BaseHost,
        in_debug_mode: bool,
    ) -> Result<T, ExecutionError> {
        // ...
    }
}

impl<T> MapExecutionErrorExt<T> for Result<T, MemoryError> {
    fn map_exec_err(
        self,
        mast_forest: &MastForest,
        node_id: MastNodeId,
        host: &impl BaseHost,
        in_debug_mode: bool,
    ) -> Result<T, ExecutionError> {
        // ...
    }
}
```

File: processor/src/fast/call_and_dyn.rs [hunk 10]
```diff
@@ -68,9 +70,8 @@ impl FastProcessor {
             self.caller_hash = callee_hash;
 
             // Initialize the frame pointer in memory for the new context.
-            if let Err(err) = self.memory.write_element(new_ctx, FMP_ADDR, FMP_INIT_VALUE, &err_ctx)
-            {
-                return ControlFlow::Break(BreakReason::Err(ExecutionError::MemoryError(err)));
+            if let Err(err) = self.memory.write_element(new_ctx, FMP_ADDR, FMP_INIT_VALUE) {
+                return ControlFlow::Break(BreakReason::Err(ExecutionError::MemoryErrorNoCtx(err)));
             }
```
Comment (plafer) [inline processor/src/fast/call_and_dyn.rs]: Why do we use `MemoryErrorNoCtx` here? I actually forget, but previously we passed an `ErrorContext`, so wouldn't this failing have given a diagnostic showing the `call.xyz` line as where the error originated? Whereas now we won't get any diagnostic if there's a memory error, right?

Same question applies to other uses of `MemoryErrorNoCtx` in this file.

File: processor/src/fast/external.rs [hunk 11]
```diff
@@ -50,24 +53,38 @@ impl FastProcessor {
 
     /// Analogous to [`Process::resolve_external_node`](crate::Process::resolve_external_node), but
     /// for asynchronous execution.
+    ///
+    /// Note: Since we're resolving an external node, we don't have meaningful error context
+    /// (no "current" forest/node). We pass the external node's parent forest and node_id for
+    /// error context, with debug mode disabled for this resolution step.
```
Comment (plafer) [inline processor/src/fast/external.rs]: Not sure exactly what is meant here, but note that the `FastProcessor` in `next` currently does the "wrong thing" with respect to external node diagnostics (documented in #2476).

i.e. there *is* something we can do with respect to external node diagnostics because we used to do it with `Process` (see [here](https://github.com/0xMiden/miden-vm/blob/f9fb1be9e03d7db7b0f5e2c9c066ff8c7ae009b4/processor/src/lib.rs#L1017-L1045)). That being said, we shouldn't fix this is in this PR, but might be worth adjusting the comment (i.e. we're not outputting the diagnostics we should currently, but this is tracked with #2476)

File: processor/src/fast/memory.rs [hunk 12]
```diff
@@ -96,11 +87,10 @@ impl Memory {
         &mut self,
         ctx: ContextId,
         addr: Felt,
-        clk: RowIndex,
+        _clk: RowIndex,
```
Comment (plafer) [inline processor/src/fast/memory.rs:90]: remove?

File: Makefile [hunk 13]
```diff
@@ -234,9 +234,9 @@ run-examples: exec ## Runs all masm examples to verify they execute correctly
 # --- benchmarking --------------------------------------------------------------------------------
 
 .PHONY: check-bench
-check-bench: ## Builds all benchmarks (incl. those needing no_err_ctx)
-	cargo check --benches --features internal,no_err_ctx
+check-bench: ## Builds all benchmarks
+	cargo check --benches --features internal
```
Comment (plafer) [inline Makefile:238]: I'm getting a ~13% performance regression on the `program_execution_fast` (`blake3_1to1`) benchmark, though I didn't investigate further why. Any idea what might be causing this?

File: processor/src/errors.rs (hunk 8 above)
Comment (bitwalker) [reply processor/src/errors.rs]: Agreed, I would think if we're already on the error path, then the expense of extracting maximal context for the error is always worth it, since without it, there is very little to indicate what actually went wrong.

File: Makefile (hunk 13 above)
Comment (huitseeker) [reply Makefile:238]: Thanks for the report! I reproduced the slowdown. I believe the issue is LLVM was not fully optimizing away closure setup overhead in `map_err` calls. Even when the closure is never invoked (success path), the compiler was generating code for closure environment capture.

I replaced `map_err` closures with explicit `match` patterns in all error extension traits (`processor/src/errors.rs`). This gives LLVM clearer visibility into control flow, and allows it to eliminate error handling overhead on the success path.

**Before:**
```rust
self.map_err(|err| {
    let (label, source_file) = get_label_and_source_file(...);
    ExecutionError::OperationError { label, source_file, err }
})
```

**After:**
```rust
match self {
    Ok(v) => Ok(v),
    Err(err) => {
        let (label, source_file) = get_label_and_source_file(...);
        Err(ExecutionError::OperationError { label, source_file, err })
    },
}
```

I added a couple of other changes (inline annotations, hoisting `in_debug_mode` better).

### Full Benchmark Measurements

Each commit was benchmarked 3 times with 5s warm-up and 10s measurement time.

| Commit | Description | Run 1 | Run 2 | Run 3 | Average | Std Dev | vs Baseline |
|--------|-------------|-------|-------|-------|---------|---------|-------------|
| `origin/next` + `no_err_ctx` | Baseline (feature flag) | 3.052 ms | 3.057 ms | 3.042 ms | **3.050 ms** | ±0.008 ms | - |
| `7c11c959e` | Before fix (with regression) | 3.466 ms | 3.570 ms | 3.420 ms | **3.485 ms** | ±0.076 ms | +14.3% |
| `1ff422bb0` | After fix | 3.054 ms | 3.043 ms | 3.058 ms | **3.052 ms** | ±0.008 ms | +0.07% |
| `17ce096aa` | Tip (with trait consolidation) | 3.104 ms | 3.078 ms | 3.076 ms | **3.086 ms** | ±0.016 ms | +1.2% |

<details><summary> benchmark </summary>

```bash
# Run the fast execution benchmark
cargo bench --bench program_execution_fast --features internal

# To compare against baseline with no_err_ctx feature (if available)
cargo bench --bench program_execution_fast --features internal,no_err_ctx
```

</details>

File: processor/src/chiplets/memory/errors.rs (hunk 2 above)
Comment (huitseeker) [reply processor/src/chiplets/memory/errors.rs]: Removed!

File: processor/src/errors.rs (hunk 8 above)
Comment (huitseeker) [reply processor/src/errors.rs]: Fixed

File: processor/src/errors.rs (hunk 9 above)
Comment (huitseeker) [reply processor/src/errors.rs]: Thanks! I was very unsure about this initially, because the structs required different arguments at different points in the edition of this PR (see PR description), but turns out this works out nicely enough. See 17ce096aac8867019acb7e6b2b377a8b465beedd

File: processor/src/fast/memory.rs (hunk 12 above)
Comment (huitseeker) [reply processor/src/fast/memory.rs:90]: It's part of the `MemoryInterface` trait.

File: processor/src/fast/external.rs (hunk 11 above)
Comment (huitseeker) [reply processor/src/fast/external.rs]: Edited!

File: processor/src/fast/call_and_dyn.rs (hunk 10 above)
Comment (huitseeker) [reply processor/src/fast/call_and_dyn.rs]: Fixed. This file now uses `map_exec_err()` with full context. Memory errors here will include source diagnostics. `crypto_ops.rs` and `operations/utils.rs` still use `MemoryErrorNoCtx`. These functions don't have access to `MastForest`/`node_id`/`host` parameters.

File: processor/src/chiplets/bitwise/mod.rs (hunk 3 above)
Comment (huitseeker) [reply processor/src/chiplets/bitwise/mod.rs:123]: #2575

File: processor/src/tests/mod.rs (hunk 7 above)
Comment (huitseeker) [reply processor/src/tests/mod.rs:128]: #2578

File: processor/src/fast/mod.rs (hunk 6 above)
Comment (huitseeker) [reply processor/src/fast/mod.rs]: #2575

**Comment by plafer** [comment]
@huitseeker 3 commits are not signed (so we can't merge)
