### PR TITLE
fix(assembly): incorrect handling of export aliases in name resolution

### LINKED ISSUE #1451: Fix re-exports from aliased module
As identified by @bobbinth, as of v0.10.3, the following fails:

```
use.miden::contracts::wallets::basic->basic_wallet

export.basic_wallet::receive_asset
export.basic_wallet::send_asset
```

Note that module aliases work fine (as enforced by [the `module_alias` test](https://github.com/0xPolygonMiden/miden-vm/blob/60ccf239fe9b77191d3c7173474daeacfd1f2ea4/assembly/src/tests.rs#L1827-L1870)); it is specifically re-exporting a procedure from a module alias that is broken.

### PR DESCRIPTION
**Pull request by bitwalker**
Closes #1451

### CODE REVIEW

File: assembly/src/library/tests.rs [hunk 1]
```diff
@@ -68,6 +68,7 @@ fn library_exports() -> Result<(), Report> {
         end
     "#;
     let bar = parse_module!(&context, "lib2::bar", bar);
+    std::println!("{bar}");
```
Comment (bobbinth) [inline assembly/src/library/tests.rs]: I think this is probably a dubbing leftover?

File: assembly/src/assembler/linker/rewrites/module.rs [hunk 2]
```diff
@@ -68,8 +68,13 @@ impl<'a, 'b: 'a> ModuleRewriter<'a, 'b> {
...
         };
         match self.resolver.resolve_target(&caller, target) {
-            Err(err) => return ControlFlow::Break(err),
-            Ok(ResolvedTarget::Phantom(_)) => (),
+            Err(err) => {
+                log::error!(target: "linker", "    | failed to resolve target {target}");
+                return ControlFlow::Break(err);
+            },
+            Ok(ResolvedTarget::Phantom(_)) => {
+                log::warn!(target: "linker", "    | resolved phantom target {target}");
```
Comment (bobbinth) [inline assembly/src/assembler/linker/rewrites/module.rs:76]: Question: does "phantom" now mean "dynamic"?

**Review by bobbinth — APPROVED** [review]
Looks good! Thank you! I left two small comments inline.

File: assembly/src/library/tests.rs (hunk 1 above)
Comment (bitwalker) [reply assembly/src/library/tests.rs]: Oops, thanks

File: assembly/src/assembler/linker/rewrites/module.rs (hunk 2 above)
Comment (bitwalker) [reply assembly/src/assembler/linker/rewrites/module.rs:76]: Yes and no - a phantom reference is inherently dynamically-linked, because it refers to a MAST root we don't have any information for. However, the reason we call this a phantom reference and not a dynamic one, is because we want to be clear that the reference is to something unknown to us, a definition we can't see.

We could call it `Dynamic`, but that wouldn't fully capture the semantics of what `Phantom` means in the linker.

Comment (bobbinth) [reply assembly/src/assembler/linker/rewrites/module.rs:76]: Makes sense. Let's keep it as `Phantom` then.
